In [1]:
import pandas as pd

# Let's read the data

In [2]:
weather=pd.read_csv('weatherAUS.csv')

## shape

In [4]:
weather.shape

(142193, 24)

## head()

In [21]:
weather.head(60)

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
0,2008-12-01,Albury,13.4,22.9,0.6,NaN,NaN,W,44.0,W,...,22.0,1007.7,1007.1,8.0,NaN,16.9,21.8,No,0.0,No
1,2008-12-02,Albury,7.4,25.1,0.0,NaN,NaN,WNW,44.0,NNW,...,25.0,1010.6,1007.8,NaN,NaN,17.2,24.3,No,0.0,No
2,2008-12-03,Albury,12.9,25.7,0.0,NaN,NaN,WSW,46.0,W,...,30.0,1007.6,1008.7,NaN,2.0,21.0,23.2,No,0.0,No
3,2008-12-04,Albury,9.2,28.0,0.0,NaN,NaN,NE,24.0,SE,...,16.0,1017.6,1012.8,NaN,NaN,18.1,26.5,No,1.0,No
4,2008-12-05,Albury,17.5,32.3,1.0,NaN,NaN,W,41.0,ENE,...,33.0,1010.8,1006.0,7.0,8.0,17.8,29.7,No,0.2,No
5,2008-12-06,Albury,14.6,29.7,0.2,NaN,NaN,WNW,56.0,W,...,23.0,1009.2,1005.4,NaN,NaN,20.6,28.9,No,0.0,No
6,2008-12-07,Albury,14.3,25.0,0.0,NaN,NaN,W,50.0,SW,...,19.0,1009.6,1008.2,1.0,NaN,18.1,24.6,No,0.0,No
7,2008-12-08,Albury,7.7,26.7,0.0,NaN,NaN,W,35.0,SSE,...,19.0,1013.4,1010.1,NaN,NaN,16.3,25.5,No,0.0,No
8,2008-12-09,Albury,9.7,31.9,0.0,NaN,NaN,NNW,80.0,SE,...,9.0,1008.9,1003.6,NaN,NaN,18.3,30.2,No,1.4,Yes
9,2008-12-10,Albury,13.1,30.1,1.4,NaN,NaN,W,28.0,S,...,27.0,1007.0,1005.7,NaN,NaN,20.1,28.2,Yes,0.0,No
10,2008-12-11,Albury,13.4,30.4,0.0,NaN,NaN,N,30.0,SSE,...,22.0,1011.8,1008.7,NaN,NaN,20.4,28.8,No,2.2,Yes
11,2008-12-12,Albury,15.9,21.7,2.2,NaN,NaN,NNE,31.0,NE,...,91.0,1010.5,1004.2,8.0,8.0,15.9,17.0,Yes,15.6,Yes
12,2008-12-13,Albury,15.9,18.6,15.6,NaN,NaN,W,61.0,NNW,...,93.0,994.3,993.0,8.0,8.0,17.4,15.8,Yes,3.6,Yes
13,2008-12-14,Albury,12.6,21.0,3.6,NaN,NaN,SW,44.0,W,...,43.0,1001.2,1001.8,NaN,7.0,15.8,19.8,Yes,0.0,No
14,2008-12-16,Albury,9.8,27.7,NaN,NaN,NaN,WNW,50.0,NaN,...,28.0,1013.4,1010.3,0.0,NaN,17.3,26.2,NaN,0.0,No
15,2008-12-17,Albury,14.1,20.9,0.0,NaN,NaN,ENE,22.0,SSW,...,82.0,1012.2,1010.4,8.0,1.0,17.2,18.1,No,16.8,Yes
16,2008-12-18,Albury,13.5,22.9,16.8,NaN,NaN,W,63.0,N,...,65.0,1005.8,1002.2,8.0,1.0,18.0,21.5,Yes,10.6,Yes
17,2008-12-19,Albury,11.2,22.5,10.6,NaN,NaN,SSE,43.0,WSW,...,32.0,1009.4,1009.7,NaN,2.0,15.5,21.0,Yes,0.0,No
18,2008-12-20,Albury,9.8,25.6,0.0,NaN,NaN,SSE,26.0,SE,...,26.0,1019.2,1017.1,NaN,NaN,15.8,23.2,No,0.0,No
19,2008-12-21,Albury,11.5,29.3,0.0,NaN,NaN,S,24.0,SE,...,28.0,1019.3,1014.8,NaN,NaN,19.1,27.3,No,0.0,No
20,2008-12-22,Albury,17.1,33.0,0.0,NaN,NaN,NE,43.0,NE,...,28.0,1013.6,1008.1,NaN,1.0,24.5,31.6,No,0.0,No
21,2008-12-23,Albury,20.5,31.8,0.0,NaN,NaN,WNW,41.0,W,...,24.0,1007.8,1005.7,NaN,NaN,23.8,30.8,No,0.0,No
22,2008-12-24,Albury,15.3,30.9,0.0,NaN,NaN,N,33.0,ESE,...,23.0,1011.0,1008.2,5.0,NaN,20.9,29.0,No,0.0,No
23,2008-12-25,Albury,12.6,32.4,0.0,NaN,NaN,W,43.0,E,...,17.0,1012.9,1010.1,NaN,NaN,21.5,31.2,No,0.0,No
24,2008-12-26,Albury,16.2,33.9,0.0,NaN,NaN,WSW,35.0,SE,...,19.0,1010.9,1007.6,NaN,1.0,23.2,33.0,No,0.0,No
25,2008-12-27,Albury,16.9,33.0,0.0,NaN,NaN,WSW,57.0,NaN,...,28.0,1006.8,1003.6,NaN,1.0,26.6,31.2,No,0.0,No
26,2008-12-28,Albury,20.1,32.7,0.0,NaN,NaN,WNW,48.0,N,...,15.0,1005.2,1001.7,NaN,NaN,24.6,32.1,No,0.0,No
27,2008-12-29,Albury,19.7,27.2,0.0,NaN,NaN,WNW,46.0,NW,...,22.0,1004.8,1004.2,NaN,NaN,21.6,26.1,No,1.2,Yes
28,2008-12-30,Albury,12.5,24.2,1.2,NaN,NaN,WNW,50.0,WSW,...,70.0,1005.6,1003.4,8.0,8.0,12.5,18.2,Yes,0.8,No
29,2008-12-31,Albury,12.0,24.4,0.8,NaN,NaN,W,39.0,WNW,...,28.0,1006.1,1005.1,1.0,NaN,16.9,22.7,No,0.0,No
30,2009-01-01,Albury,11.3,26.5,0.0,NaN,NaN,WNW,56.0,W,...,26.0,1004.5,1003.2,NaN,NaN,19.7,25.7,No,0.0,No
31,2009-01-02,Albury,9.6,23.9,0.0,NaN,NaN,W,41.0,WSW,...,22.0,1014.4,1013.1,NaN,NaN,14.9,22.1,No,0.0,No
32,2009-01-03,Albury,10.5,28.8,0.0,NaN,NaN,SSE,26.0,SSE,...,22.0,1018.7,1014.8,NaN,NaN,17.1,26.5,No,0.0,No
33,2009-01-04,Albury,12.3,34.6,0.0,NaN,NaN,WNW,37.0,SSE,...,12.0,1015.1,1010.3,NaN,NaN,20.7,33.9,No,0.0,No
34,2009-01-05,Albury,12.9,35.8,0.0,NaN,NaN,WNW,41.0,ENE,...,9.0,1012.6,1009.2,NaN,NaN,22.4,34.4,No,0.0,No
35,2009-01-06,Albury,13.7,37.9,0.0,NaN,NaN,W,52.0,SE,...,8.0,1010.9,1006.7,NaN,NaN,23.1,36.8,No,0.0,No
36,2009-01-07,Albury,16.1,38.9,0.0,NaN,NaN,W,57.0,E,...,12.0,1007.0,1002.7,NaN,NaN,25.2,38.4,No,0.0,No
37,2009-01-08,Albury,14.0,28.3,0.0,NaN,NaN,W,48.0,W,...,15.0,1011.9,1010.9,NaN,NaN,17.9,27.6,No,0.0,No
38,2009-01-09,Albury,12.5,28.4,0.0,NaN,NaN,NE,37.0,SSE,...,16.0,1017.8,1013.7,NaN,NaN,17.2,26.6,No,0.0,No
39,2009-01-10,Albury,17.0,30.8,0.0,NaN,NaN,NE,37.0,NNE,...,24.0,1013.4,1008.1,NaN,NaN,20.2,29.3,No,0.0,No
40,2009-01-11,Albury,16.9,32.0,0.0,NaN,NaN,S,31.0,SSE,...,31.0,1009.9,1006.8,NaN,NaN,22.8,30.0,No,0.0,No
41,2009-01-12,Albury,17.3,34.7,0.0,NaN,NaN,SW,35.0,SE,...,16.0,1014.1,1012.1,NaN,NaN,24.2,33.2,No,0.0,No
42,2009-01-13,Albury,17.2,37.7,0.0,NaN,NaN,NNW,35.0,SE,...,19.0,1015.7,1010.9,NaN,NaN,24.3,35.7,No,0.0,No
43,2009-01-14,Albury,17.4,43.0,0.0,NaN,NaN,NW,39.0,SSE,...,8.0,1011.6,1006.9,NaN,NaN,25.6,41.5,No,0.0,No
44,2009-01-15,Albury,19.8,32.7,0.0,NaN,NaN,WNW,44.0,W,...,28.0,1008.4,1009.2,NaN,NaN,27.6,27.1,No,0.0,No
45,2009-01-16,Albury,14.9,26.7,0.0,NaN,NaN,SW,56.0,WSW,...,20.0,1014.1,1012.7,NaN,NaN,18.0,25.5,No,0.0,No
46,2009-01-17,Albury,10.5,28.4,0.0,NaN,NaN,SE,33.0,SE,...,16.0,1019.7,1017.4,NaN,NaN,16.0,25.8,No,0.0,No
47,2009-01-18,Albury,11.3,32.2,0.0,NaN,NaN,WNW,28.0,ENE,...,17.0,1019.7,1016.2,NaN,NaN,20.9,30.5,No,0.0,No
48,2009-01-19,Albury,13.9,36.6,0.0,NaN,NaN,WNW,39.0,SSE,...,10.0,1015.8,1010.6,NaN,NaN,22.0,34.4,No,0.0,No
49,2009-01-20,Albury,18.6,39.9,0.0,NaN,NaN,NNW,61.0,SSE,...,21.0,1010.1,1004.8,NaN,NaN,26.8,37.7,No,0.8,No
50,2009-01-21,Albury,19.3,38.1,0.8,NaN,NaN,NNW,61.0,NE,...,17.0,1009.6,1005.9,NaN,NaN,27.3,36.1,No,0.6,No
51,2009-01-22,Albury,24.4,34.0,0.6,NaN,NaN,NW,98.0,N,...,39.0,1005.3,997.8,4.0,1.0,26.1,33.1,No,6.4,Yes
52,2009-01-23,Albury,18.8,35.2,6.4,NaN,NaN,WNW,52.0,S,...,28.0,1007.9,1003.9,NaN,NaN,22.8,33.0,Yes,0.0,No
53,2009-01-24,Albury,20.8,30.6,0.0,NaN,NaN,W,54.0,W,...,21.0,1005.4,1007.6,NaN,NaN,23.3,29.7,No,0.0,No
54,2009-01-25,Albury,14.0,34.3,0.0,NaN,NaN,WSW,24.0,ESE,...,10.0,1016.5,1014.6,NaN,NaN,21.2,32.1,No,0.0,No
55,2009-01-26,Albury,15.7,38.4,0.0,NaN,NaN,S,33.0,SSE,...,12.0,1017.7,1014.6,NaN,NaN,23.4,36.5,No,0.0,No
56,2009-01-27,Albury,18.5,38.2,0.0,NaN,NaN,NNE,31.0,SE,...,25.0,1017.8,1014.1,NaN,NaN,25.8,36.2,No,0.0,No
57,2009-01-28,Albury,20.4,40.7,0.0,NaN,NaN,N,37.0,E,...,15.0,1014.9,1011.6,NaN,NaN,28.2,39.2,No,0.0,No
58,2009-01-29,Albury,21.8,41.5,0.0,NaN,NaN,SW,24.0,ESE,...,13.0,1015.7,1011.8,NaN,NaN,29.0,40.1,No,0.0,No
59,2009-01-30,Albury,22.3,42.9,0.0,NaN,NaN,NNE,28.0,ESE,...,11.0,1014.6,1010.2,NaN,NaN,29.2,41.2,No,0.0,No

## tail()

In [11]:
weather.tail(7)

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
142186,2017-06-18,Uluru,8.0,20.7,0.0,NaN,NaN,ESE,41.0,SE,...,32.0,1028.1,1024.3,NaN,7.0,11.6,20.0,No,0.0,No
142187,2017-06-19,Uluru,7.4,20.6,0.0,NaN,NaN,E,35.0,ESE,...,33.0,1027.2,1023.3,NaN,NaN,11.0,20.3,No,0.0,No
142188,2017-06-20,Uluru,3.5,21.8,0.0,NaN,NaN,E,31.0,ESE,...,27.0,1024.7,1021.2,NaN,NaN,9.4,20.9,No,0.0,No
142189,2017-06-21,Uluru,2.8,23.4,0.0,NaN,NaN,E,31.0,SE,...,24.0,1024.6,1020.3,NaN,NaN,10.1,22.4,No,0.0,No
142190,2017-06-22,Uluru,3.6,25.3,0.0,NaN,NaN,NNW,22.0,SE,...,21.0,1023.5,1019.1,NaN,NaN,10.9,24.5,No,0.0,No
142191,2017-06-23,Uluru,5.4,26.9,0.0,NaN,NaN,N,37.0,SE,...,24.0,1021.0,1016.8,NaN,NaN,12.5,26.1,No,0.0,No
142192,2017-06-24,Uluru,7.8,27.0,0.0,NaN,NaN,SE,28.0,SSE,...,24.0,1019.4,1016.5,3.0,2.0,15.1,26.0,No,0.0,No

## sample()

In [15]:
weather.sample(10)

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
136778,2010-11-05,Darwin,25.1,32.7,0.0,7.0,8.5,NNW,31.0,SE,...,59.0,1010.4,1007.2,6.0,7.0,28.8,29.4,No,0.0,No
46057,2012-08-12,Canberra,4.1,14.5,0.0,3.7,9.2,SSE,48.0,SSE,...,36.0,1027.6,1024.8,3.0,NaN,8.9,14.3,No,0.0,No
58077,2012-10-06,Bendigo,9.1,11.2,0.4,NaN,NaN,SSW,33.0,SSE,...,93.0,1017.3,1014.4,8.0,8.0,9.6,9.5,No,8.2,Yes
453,2010-03-06,Albury,18.8,30.3,20.6,NaN,NaN,WSW,39.0,W,...,48.0,1010.0,1009.0,8.0,1.0,22.3,29.4,Yes,5.8,Yes
129160,2015-07-25,Hobart,5.4,13.2,0.0,2.2,5.7,NNW,41.0,NW,...,49.0,1002.4,1001.5,3.0,6.0,7.3,12.1,No,3.4,Yes
24065,2010-04-18,Penrith,14.2,26.7,0.0,NaN,NaN,E,24.0,NE,...,47.0,NaN,NaN,NaN,NaN,19.8,26.3,No,0.0,No
132665,2016-11-09,Launceston,4.1,19.8,0.0,NaN,NaN,NNW,33.0,N,...,53.0,NaN,NaN,NaN,NaN,11.5,18.8,No,0.0,No
48391,2010-09-07,Tuggeranong,0.0,14.0,0.0,NaN,NaN,S,28.0,SSW,...,47.0,1024.2,1022.5,NaN,NaN,7.9,12.9,No,0.0,No
37707,2014-05-12,WaggaWagga,3.7,19.7,0.0,1.2,9.7,ENE,24.0,E,...,50.0,1031.0,1028.6,1.0,3.0,9.6,19.3,No,0.0,No
2474,2016-01-01,Albury,20.4,37.6,0.0,NaN,NaN,ENE,54.0,NaN,...,17.0,1013.4,1009.2,7.0,3.0,26.1,36.7,No,0.4,No

## columns

In [16]:
weather.columns

Index(['Date', 'Location', 'MinTemp', 'MaxTemp', 'Rainfall', 'Evaporation',
       'Sunshine', 'WindGustDir', 'WindGustSpeed', 'WindDir9am', 'WindDir3pm',
       'WindSpeed9am', 'WindSpeed3pm', 'Humidity9am', 'Humidity3pm',
       'Pressure9am', 'Pressure3pm', 'Cloud9am', 'Cloud3pm', 'Temp9am',
       'Temp3pm', 'RainToday', 'RISK_MM', 'RainTomorrow'],
      dtype='object')

## info()

In [17]:
weather.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 142193 entries, 0 to 142192
Data columns (total 24 columns):
Date             142193 non-null object
Location         142193 non-null object
MinTemp          141556 non-null float64
MaxTemp          141871 non-null float64
Rainfall         140787 non-null float64
Evaporation      81350 non-null float64
Sunshine         74377 non-null float64
WindGustDir      132863 non-null object
WindGustSpeed    132923 non-null float64
WindDir9am       132180 non-null object
WindDir3pm       138415 non-null object
WindSpeed9am     140845 non-null float64
WindSpeed3pm     139563 non-null float64
Humidity9am      140419 non-null float64
Humidity3pm      138583 non-null float64
Pressure9am      128179 non-null float64
Pressure3pm      128212 non-null float64
Cloud9am         88536 non-null float64
Cloud3pm         85099 non-null float64
Temp9am          141289 non-null float64
Temp3pm          139467 non-null float64
RainToday        140787 non-null object
RISK_MM          142193 non-null float64
RainTomorrow     142193 non-null object
dtypes: float64(17), object(7)
memory usage: 26.0+ MB

## describe()

In [20]:
weather.describe(include='all')

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
count,142193,142193,141556.000000,141871.000000,140787.000000,81350.000000,74377.000000,132863,132923.000000,132180,...,138583.000000,128179.000000,128212.000000,88536.000000,85099.000000,141289.000000,139467.000000,140787,142193.000000,142193
unique,3436,49,NaN,NaN,NaN,NaN,NaN,16,NaN,16,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,2
top,2017-05-13,Canberra,NaN,NaN,NaN,NaN,NaN,W,NaN,N,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,No
freq,49,3418,NaN,NaN,NaN,NaN,NaN,9780,NaN,11393,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,109332,NaN,110316
mean,NaN,NaN,12.186400,23.226784,2.349974,5.469824,7.624853,NaN,39.984292,NaN,...,51.482606,1017.653758,1015.258204,4.437189,4.503167,16.987509,21.687235,NaN,2.360682,NaN
std,NaN,NaN,6.403283,7.117618,8.465173,4.188537,3.781525,NaN,13.588801,NaN,...,20.797772,7.105476,7.036677,2.887016,2.720633,6.492838,6.937594,NaN,8.477969,NaN
min,NaN,NaN,-8.500000,-4.800000,0.000000,0.000000,0.000000,NaN,6.000000,NaN,...,0.000000,980.500000,977.100000,0.000000,0.000000,-7.200000,-5.400000,NaN,0.000000,NaN
25%,NaN,NaN,7.600000,17.900000,0.000000,2.600000,4.900000,NaN,31.000000,NaN,...,37.000000,1012.900000,1010.400000,1.000000,2.000000,12.300000,16.600000,NaN,0.000000,NaN
50%,NaN,NaN,12.000000,22.600000,0.000000,4.800000,8.500000,NaN,39.000000,NaN,...,52.000000,1017.600000,1015.200000,5.000000,5.000000,16.700000,21.100000,NaN,0.000000,NaN
75%,NaN,NaN,16.800000,28.200000,0.800000,7.400000,10.600000,NaN,48.000000,NaN,...,66.000000,1022.400000,1020.000000,7.000000,7.000000,21.600000,26.400000,NaN,0.800000,NaN
max,NaN,NaN,33.900000,48.100000,371.000000,145.000000,14.500000,NaN,135.000000,NaN,...,100.000000,1041.000000,1039.600000,9.000000,9.000000,40.200000,46.700000,NaN,371.000000,NaN